/*
 * Apicurio Registry API [v2]
 *
 * Apicurio Registry is a datastore for standard event schemas and API designs. Apicurio Registry enables developers to manage and share the structure of their data using a REST interface. For example, client applications can dynamically push or pull the latest updates to or from the registry without needing to redeploy. Apicurio Registry also enables developers to create rules that govern how registry content can evolve over time. For example, this includes rules for content validation and version compatibility.  The Apicurio Registry REST API enables client applications to manage the artifacts in the registry. This API provides create, read, update, and delete operations for schema and API artifacts, rules, versions, and metadata.   The supported artifact types include: - Apache Avro schema - AsyncAPI specification - Google protocol buffers - GraphQL schema - JSON Schema - Kafka Connect schema - OpenAPI specification - Web Services Description Language - XML Schema Definition   **Important**: The Apicurio Registry REST API is available from `https://MY-REGISTRY-URL/apis/registry/v2` by default. Therefore you must prefix all API operation paths with `../apis/registry/v2` in this case. For example: `../apis/registry/v2/ids/globalIds/{globalId}`. 
 *
 * The version of the OpenAPI document: 2.2.5.Final
 * Contact: apicurio@lists.jboss.org
 * Generated by: https://openapi-generator.tech
 */

/// Limits : List of limitations on used resources, that are applied on the current instance of Registry. Keys represent the resource type and are suffixed by the corresponding unit. Values are integers. Only non-negative values are allowed, with the exception of -1, which means that the limit is not applied.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Limits {
    #[serde(rename = "maxTotalSchemasCount", skip_serializing_if = "Option::is_none")]
    pub max_total_schemas_count: Option<i64>,
    #[serde(rename = "maxSchemaSizeBytes", skip_serializing_if = "Option::is_none")]
    pub max_schema_size_bytes: Option<i64>,
    #[serde(rename = "maxArtifactsCount", skip_serializing_if = "Option::is_none")]
    pub max_artifacts_count: Option<i64>,
    #[serde(rename = "maxVersionsPerArtifactCount", skip_serializing_if = "Option::is_none")]
    pub max_versions_per_artifact_count: Option<i64>,
    #[serde(rename = "maxArtifactPropertiesCount", skip_serializing_if = "Option::is_none")]
    pub max_artifact_properties_count: Option<i64>,
    #[serde(rename = "maxPropertyKeySizeBytes", skip_serializing_if = "Option::is_none")]
    pub max_property_key_size_bytes: Option<i64>,
    #[serde(rename = "maxPropertyValueSizeBytes", skip_serializing_if = "Option::is_none")]
    pub max_property_value_size_bytes: Option<i64>,
    #[serde(rename = "maxArtifactLabelsCount", skip_serializing_if = "Option::is_none")]
    pub max_artifact_labels_count: Option<i64>,
    #[serde(rename = "maxLabelSizeBytes", skip_serializing_if = "Option::is_none")]
    pub max_label_size_bytes: Option<i64>,
    #[serde(rename = "maxArtifactNameLengthChars", skip_serializing_if = "Option::is_none")]
    pub max_artifact_name_length_chars: Option<i64>,
    #[serde(rename = "maxArtifactDescriptionLengthChars", skip_serializing_if = "Option::is_none")]
    pub max_artifact_description_length_chars: Option<i64>,
    #[serde(rename = "maxRequestsPerSecondCount", skip_serializing_if = "Option::is_none")]
    pub max_requests_per_second_count: Option<i64>,
}

impl Limits {
    /// List of limitations on used resources, that are applied on the current instance of Registry. Keys represent the resource type and are suffixed by the corresponding unit. Values are integers. Only non-negative values are allowed, with the exception of -1, which means that the limit is not applied.
    pub fn new() -> Limits {
        Limits {
            max_total_schemas_count: None,
            max_schema_size_bytes: None,
            max_artifacts_count: None,
            max_versions_per_artifact_count: None,
            max_artifact_properties_count: None,
            max_property_key_size_bytes: None,
            max_property_value_size_bytes: None,
            max_artifact_labels_count: None,
            max_label_size_bytes: None,
            max_artifact_name_length_chars: None,
            max_artifact_description_length_chars: None,
            max_requests_per_second_count: None,
        }
    }
}


